# SVD decomposition with `scipy`

Import the required modules

In [2]:
import scipy.linalg as la
import numpy as np

Generate a random 5x4 matrix

In [3]:
A = np.random.rand(5,4)
A

array([[0.15977966, 0.38773577, 0.64323738, 0.25588879],
       [0.76848385, 0.95149534, 0.3957631 , 0.21566664],
       [0.35692057, 0.83997511, 0.65926379, 0.17609033],
       [0.78812465, 0.84790069, 0.9671166 , 0.63375789],
       [0.01647767, 0.61227285, 0.45562345, 0.59832928]])

## `<numpy|scipy>.linalg.svd` 

Equivalent implementations:
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html



### Full SVD (`full_matrices = True` - default)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [4]:
U, s, VT = np.linalg.svd(A)
#U, s, VT = la.svd(A)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 5)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [5]:
S = np.zeros(A.shape)
for i in range(len(s)):
    S[i, i] = s[i]
S

array([[2.57443127, 0.        , 0.        , 0.        ],
       [0.        , 0.62808089, 0.        , 0.        ],
       [0.        , 0.        , 0.3790305 , 0.        ],
       [0.        , 0.        , 0.        , 0.32353369],
       [0.        , 0.        , 0.        , 0.        ]])

In [11]:
S = la.diagsvd(s, A.shape[0], A.shape[1])
S

array([[2.57443127, 0.        , 0.        , 0.        ],
       [0.        , 0.62808089, 0.        , 0.        ],
       [0.        , 0.        , 0.3790305 , 0.        ],
       [0.        , 0.        , 0.        , 0.32353369],
       [0.        , 0.        , 0.        , 0.        ]])

Reconstruct the matrix $A$

In [7]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 7.024584e-16


### Thin SVD (`full_matrices = False`)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times q}, S \in \mathbb{R}^{q\times q}, V \in \mathbb{R}^{n\times q}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.



In [8]:
del U, s, S, VT
U, s, VT = la.svd(A, full_matrices = False)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 4)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [9]:
S = np.diag(s)
S

array([[2.57443127, 0.        , 0.        , 0.        ],
       [0.        , 0.62808089, 0.        , 0.        ],
       [0.        , 0.        , 0.3790305 , 0.        ],
       [0.        , 0.        , 0.        , 0.32353369]])

Reconstruct the matrix $A$

In [ ]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))